# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Stag
version:      0.11
version_from: Data/Stag.pm
installdirs:  site
requires:
    IO::String:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
